/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MokExaple {
        "text": string;
    }
    interface MokH1 {
        "text": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLMokExapleElement extends Components.MokExaple, HTMLStencilElement {
    }
    var HTMLMokExapleElement: {
        prototype: HTMLMokExapleElement;
        new (): HTMLMokExapleElement;
    };
    interface HTMLMokH1Element extends Components.MokH1, HTMLStencilElement {
    }
    var HTMLMokH1Element: {
        prototype: HTMLMokH1Element;
        new (): HTMLMokH1Element;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "mok-exaple": HTMLMokExapleElement;
        "mok-h1": HTMLMokH1Element;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface MokExaple {
        "text"?: string;
    }
    interface MokH1 {
        "text"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "mok-exaple": MokExaple;
        "mok-h1": MokH1;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mok-exaple": LocalJSX.MokExaple & JSXBase.HTMLAttributes<HTMLMokExapleElement>;
            "mok-h1": LocalJSX.MokH1 & JSXBase.HTMLAttributes<HTMLMokH1Element>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
